language: csharp
solution: CouponManager.sln
mono: none
sudo: required
dist: xenial
dotnet: 2.2.203
script:
 - dotnet restore
 - dotnet build
global:
 - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
 - DOTNET_CLI_TELEMETRY_OPTOUT=1
notifications:
  email:
   - heet_mehta@hotmail.com
   - meetjanani47@gmail.com
